### ISSUE TITLE
dbGetQuery unavailable for noctua::athena

### ISSUE THREAD

**Issue by chrissuh17** [DyfanJones/noctua#102]
Hello Dyfan, 

I raised this question on stackoverflow.com as @datascientist2117; thank you for your response. 

Here is the code I currently have. 

```
library(tidyverse)
library(dplyr)
library(dbplyr)
library(odbc)
library(DBI)
library(RAthena)
library(rJava)

odbcListDrivers()
sort((unique(odbcListDrivers()[[1]])))

con <- DBI::dbConnect(
  odbc::odbc(),
  Driver             = "[Simba Athena ODBC Driver]",
  S3OutputLocation   = "[s3://bucket-folder/]",
  AwsRegion          = "[region]",
  AuthenticationType = "IAM Credentials",
  Schema             = "[schema]",
  UID                = rstudioapi::askForPassword("AWS Access Key"),
  PWD                = rstudioapi::askForPassword("AWS Secret Key"))
```
All code above is exactly the same except for the omitted values in S3OutPutLocation, AwsRegion, and Schema. 

I am currently using Simba Athena ODBC Driver Version 1.1.2

I hope this information is sufficient; please let me know if there is anything else I can provide!

**Comment by DyfanJones** [comment]
Hi @chrissuh17 perfect :) I know the issue now :D Both `RAthena` and `noctua` create the class `AthenaConnection` however they work slightly differently under the hood. `RAthena` uses `python's` `boto3` and `noctua` uses `R's` `paws`.

So what is happening is R is getting confused what class to use. So if you remove `RAthena` from your loaded packages `noctua` should would for example:

```
library(DBI)

con <- dbConnect(noctua::athena())

dbGetQuery(con, "select * from some_tbl")
```

**Comment by chrissuh17** [comment]
It's working now! Thank you very much for your help.

**Comment by DyfanJones** [comment]
Happy to help, I hope you enjoy using the package. Please feel free to raise any feature requests :)

Will close this ticket now :)
