### ISSUE TITLE
Date time methods from dbplyr

### ISSUE THREAD

**Issue by OssiLehtinen** [DyfanJones/noctua#107]
Hi @DyfanJones, I'm sure you're aware of this, but anyway, the funtions refrenced in https://github.com/DyfanJones/RAthena/issues/121 should be implemented in noctua too.

**Comment by OssiLehtinen** [comment]
I can make a pull request tomorrow if that is helpful.

**Comment by DyfanJones** [comment]
Hi @OssiLehtinen dont worry all functionality in RAthena will be built in `noctua` 😄 . I am currently running a PR for RAthena. Once that has passed all the unit tests I will create PR for `noctua`. 

Unfortunately both packages have recently been released to the cran. So I will have to wait a little before releasing them again. I believe the rule of thumb is 1 month release intervals.

**Comment by DyfanJones** [comment]
@OssiLehtinen more than happy if you wish to create the PR. My current thought process is: https://github.com/DyfanJones/RAthena/pull/122. Please let me know if you wish to replicate this for `noctua`

**Comment by OssiLehtinen** [comment]
I'll make a PR shortly.

**Comment by DyfanJones** [comment]
Closing this issue. Thanks @OssiLehtinen for making your contribution and fixing this issue :D
