### ISSUE TITLE
uuid library versioning

### ISSUE THREAD

**Issue by michaelhogersnplm** [DyfanJones/noctua#128]
First, noctua is excellent and very impressive!

Just a slight improvement, the DESCRIPTION file should be modified slightly to suggest or require that the uuid library is of version 0.1-4. Any earlier version of uuid does not allow the use of the **n** argument when using uuid::UUIDgenerate() and may cause noctua::dbWriteTable to fail.

Best regards,

Michael

**Comment by DyfanJones** [comment]
Thanks @michaelhogersnplm i will add the versioning of uuid in the next release :)
