### ISSUE TITLE
Feature idea/request: Optionally disable querying glue for the whole data catalog in rstudio when dbConnect:ing

### ISSUE THREAD

**Issue by OssiLehtinen** [DyfanJones/noctua#136]
One speculative idea: would it make sense to allow a user to optionally skip reading in the glue catalog when running dbConnect in rstudio?

Of course it is often helpful to have, for example, the data catalog available for browsing in the connections pane in Rstudio.
However, when the catalog becomes very large, it can take pretty long to establish the connection (a minute or so in my case, I think some lake formation shares make things worse), and often one doesn't need the catalog for anything. In interactive work this kind of a delay can be a bit annoying, but obviously nothing too dangerous.

So, what do you think, would this be doable, and would it make sense to implement something like this? I'm unfortunately pretty clueless with the interaction with rstudio, so not sure what this would require.

**Comment by DyfanJones** [comment]
I don't see why not. When you are out side of RStudio (i.e. jupyter lab) glue catalog isn't called.

**Comment by OssiLehtinen** [comment]
Great!

**Comment by DyfanJones** [comment]
This has been merge with PR #138
