### ISSUE TITLE
Prevent Noctua from printing Data Scanned -information

### ISSUE THREAD

**Issue by vhpietil** [DyfanJones/noctua#178]
Is there a way to prevent Noctua from printing Data scanned information?

**Comment by DyfanJones** [comment]
Currently no, it was an previous feature request so it was added, however I should of added a method to make it quiet. Happy to add it in if you like :)

**Comment by vhpietil** [comment]
I would be very happy if there was an option to switch it off instead of using suppressMessages in every query :)

**Comment by DyfanJones** [comment]
So something like this:

```r
remotes::install_github("dyfanjones/noctua", ref="verbose")
```

``` r
library(DBI)
library(noctua)

con <- dbConnect(athena())

dbGetQuery(con, "select * from iris limit 5")
#>    sepal_length sepal_width petal_length petal_width species
#> 1:          5.1         3.5          1.4         0.2  setosa
#> 2:          4.9         3.0          1.4         0.2  setosa
#> 3:          4.7         3.2          1.3         0.2  setosa
#> 4:          4.6         3.1          1.5         0.2  setosa
#> 5:          5.0         3.6          1.4         0.2  setosa

noctua_options(verbose = T)

dbGetQuery(con, "select * from iris limit 5")
#> Info: (Data scanned: 3.63 KB)
#>    sepal_length sepal_width petal_length petal_width species
#> 1:          5.1         3.5          1.4         0.2  setosa
#> 2:          4.9         3.0          1.4         0.2  setosa
#> 3:          4.7         3.2          1.3         0.2  setosa
#> 4:          4.6         3.1          1.5         0.2  setosa
#> 5:          5.0         3.6          1.4         0.2  setosa
```

<sup>Created on 2022-01-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Currently not sure to have verbose set to `FALSE` for default or have the user switch to FALSE if they don't like the extra information.

**Comment by vhpietil** [comment]
Something like that would be nice

**Comment by DyfanJones** [comment]
Should all information message be optionally turned off? 🤔 Would make it consistent across the package. If that is the case then can leave the default package verbose as `TRUE` and let the user turn it off.

**Comment by vhpietil** [comment]
I guess it could be all information messages or none.

**Comment by DyfanJones** [comment]
Closing this ticket as version 2.5.0 has been pushed to the cran
