### ISSUE TITLE
`dbExistsTable()` doesn't work anymore

### ISSUE THREAD

**Issue by mgirlich** [DyfanJones/noctua#205]
It seems that Amazon changed the error when requesting metadata for a non-existing table which breaks `dbExistsTable()` (and by this unfortunately also `dbWriteTable()`. At least I now get the error

```
INFO: Error: MetadataException (HTTP 400). Entity Not Found (Service: AmazonDataCatalog; Status Code: 400; Error Code: EntityNotFoundException; Request ID: ...; Proxy: null)
```

**Comment by DyfanJones** [comment]
Hi @mgirlich  thanks for raising this.

**Comment by DyfanJones** [comment]
Sorry in the delay with this issue. I came across an error I am unable to replicate. Not sure how to resolve it. In the meantime I will do a patch release and revisit it.

**Comment by DyfanJones** [comment]
noctua 2.6.2 has been release to the cran. if this issue persists please let re-open this ticket
