### ISSUE TITLE
Connecting from noctua in a local R-Studio session throws 'no region provided error'

### ISSUE THREAD

**Issue by ricardojcc** [DyfanJones/noctua#69]
Hey Dyfan,

I apologize for coming over here with yet another issue.
  
  ### Issue Description
dbConnect() returns the following error:
Error in get_region(cfgs$credentials$profile) : No region provided

  ### Reproducible Example
library(noctua)
library(DBI)

con <- dbConnect(noctua::athena(),
                 aws_access_key_id='MyAccessKey',
                 aws_secret_access_key='MyAccessKey',
                 s3_staging_dir='s3://'my-staging-dir-us-west-2/',
                 region_name='us-west-2')

**Comment by DyfanJones** [comment]
Apologies about this. I will look into it now

**Comment by DyfanJones** [comment]
@ricardojcc in the mean time please set the region name in the environmental variable "AWS_REGION". This should work until I have fixed the package.

**Comment by ricardojcc** [comment]
Will do. Thanks @DyfanJones

**Comment by DyfanJones** [comment]
@ricardojcc PR#70 fixes this issue. Thanks for point it out to me. It was a bigger problem than I realised.  Will create unit test before merging.

**Comment by DyfanJones** [comment]
PR #70 passed unit tests and passes region correctly. If this issue persists please reopen this issue
